
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ChakraWrapper } from "@/components/ChakraWrapper";
import ColorModeToggle from "@/components/ColorModeToggle";
import { AuthProvider } from "@/contexts/AuthContext";
import Navigation from "@/components/Navigation";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import InitialLoader from "@/components/InitialLoader";
import RouteLoader from "@/components/RoutingLoader";
import ClientLayout from "@/components/ClientLayout";
import Script from "next/script";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatter",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <ClientLayout>
        <ChakraWrapper>
          <ColorModeToggle/>
          <Navigation />
        

          
          { children }
        </ChakraWrapper>
        </ClientLayout>
        </AuthProvider>
          
        
        </body>
    </html>
  );
}


